=== Web3Renewables/SolarPV-Sourcing-PoC/schemas/index_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://web3renewables.com/daily_gc_schmea.json",
  "title": "Granular Certificate Index Schmea",
  "description": "Daily and Monthly Granular Certificate Index",
  "type": "object",
  "properties": {
    "metadata": {
      "description": "Metadata Describing the Functions of this document",
      "type": "object",
      "properties": {
        "title": {
          "description": "Title of this document",
          "type": "string"
        },
        "description": {
          "description": "Description of this document",
          "type": "string"
        },
        "document_type": {
          "description": "Type of document - Is it production or development",
          "type": "string"
        },
        "web3_renewables_did": {
          "description": "DID of the Web3 Renewables Wallet Address",
          "type": "string"
        },
        "version": {
          "type": "number",
          "description": "Version Number of this Document"
        },
        "lastModified": {
          "type": "string",
          "description": "Date this document was last modified"
        }
      },
      "required": [
        "title",
        "description",
        "document_type",
        "web3_renewables_did"
      ]
    },
    "pvSystems": {
      "type": "object",
      "description": "Mapping of PV Systems to their participating days to make indexing easier",
      "patternProperties": {
        "^[a-zA-Z0-9:]*$": {
          "type": "object",
          "description": "Maps PV System DID to Index Metadata - Useful for indexing Granular Certificates by PV System DID and Role Status",
          "items": {
            "type": "object",
            "description": "PV System Metadata",
            "properties": {
              "dates_reporting": {
                "type": "array",
                "description": "Dates the PV System has reported Daily GCs",
                "item": "string"
              },
              "status": {
                "type": "string",
                "description": "Describes if the PV System has had its role revoked by Web3 Renewables - Active or Revoked. This is not the same as a GC status, however they should be the same after each monthly udpate."
              },
              "required": ["dates_reporting", "status"]
            }
          }
        }
      }
    },
    "daily": {
      "type": "object",
      "description": "All Active Daily GCs in the Index - ISO 8601 and UTC",
      "patternProperties": {
        "\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[1-2]\\d|3[0-1])T(?:[0-1]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+|)(?:Z|(?:\\+|\\-)(?:\\d{2}):?(?:\\d{2}))": {
          "type": "object",
          "description": "Date Entry that Generation Data Covers. Key is the Date (Day) in UTC format",
          "properties": {
            "entries": {
              "description": "Array of GC's that are active in the index",
              "type": "array",
              "items": {
                "type": "object",
                "description": "GC Entry Metadata",
                "properties": {
                  "cid": {
                    "description": "CID Location of the Entry (the Directory)",
                    "type": "string"
                  },
                  "fileName": {
                    "description": "File Name of the GC (can be located using 'ipfs/<cid>/<fileName>'",
                    "type": "string"
                  },
                  "pvSystemDID": {
                    "description": "DID of the PV System Asset this entry belongs too",
                    "type": "string"
                  },
                  "rawInverterCID": {
                    "description": "CID of the raw inverter data on Web3 Storage",
                    "type": "string"
                  },
                  "vcUuid": {
                    "description": "Verifiable Credential UUID on the Web3 Renewables DID Document",
                    "type": "string"
                  }
                },
                "required": [
                  "cid",
                  "fileName",
                  "pvSystemDID",
                  "rawInverterCID",
                  "vcUuid"
                ]
              }
            }
          },
          "required": ["entries"]
        }
      },
      "required": []
    },
    "monthly": {
      "type": "object",
      "description": "All Active Monthly GCs in the Index",
      "patternProperties": {
        "^[0-9-]+$": {
          "type": "object",
          "description": "Year that a GC is contained in.",
          "patternProperties": {
            "[0-9]+$": {
              "type": "object",
              "description": "Month in numerical format (e.g., 1 = January, 2 = February, 3 = March, etc..) of a GC",
              "properties": {
                "entries": {
                  "description": "Array of Monthly GC's that are active in the index",
                  "type": "array",
                  "items": {
                    "type": "object",
                    "description": "GC Entry Metadata",
                    "properties": {
                      "cid": {
                        "description": "CID Location of the Entry (the Directory)",
                        "type": "string"
                      },
                      "fileName": {
                        "description": "File Name of the Monthyl GC (can be located using 'ipfs/<cid>/<fileName>'",
                        "type": "string"
                      },
                      "pvSystemDID": {
                        "description": "DID of the PV System Asset this entry belongs too",
                        "type": "string"
                      },
                      "vcUuid": {
                        "description": "Verifiable Credential UUID on the Web3 Renewables DID Document",
                        "type": "string"
                      }
                    },
                    "required": [
                      "cid",
                      "fileName",
                      "pvSystemDID",
                      "vcUuid"
                    ]
                  }
                }
              },
              "required": ["entries"]
            }
          }
        }
      }
    }
  },
  "required": [
    "daily",
    "monthly",
    "pvSystems"
  ]
}

=== Web3Renewables/SolarPV-Sourcing-PoC/server/src/mocks/valid_index.json
{
  "metadata": {
    "title": "Web3 Renewables Granular Certificate Index",
    "description": "Index describing the location of all GCs reporting into the Web3 Renewables Index",
    "document_type": "Production",
    "web3_renewables_did": "did:ethr:ewc:0x224CbA4ae8D27Ba69793CFeFe042682B81eA77c5",
    "version": 1
  },
  "daily": {
    "2022-09-15T00:00:00.000Z": {
      "entries": [
        {
          "rawInverterCID": "bafybeie6ovvx75ycwubcdjkprkiv5jfgkoc6peckhesyhyxqzuoriaxghu",
          "vcUuid": "bb807452-5c11-4ec1-b14a-6f47fa2f86da",
          "cid": "bafybeihiwu5rwm4oh55jqqzhbotzbfzbvtn26dxadyrgsa23tbyfcgqdli",
          "fileName": "2022-09-15T00:00:00.000Z_did:ethr:volta:0x1863B5eABe907FA826C16589887440539E2F44AE_gc.json",
          "pvSystemDID": "did:ethr:volta:0x1863B5eABe907FA826C16589887440539E2F44AE",
          "certificateStatus": "Active"
        },
        {
          "rawInverterCID": "bafybeie6ovvx75ycwubcdjkprkiv5jfgkoc6peckhesyhyxqzuoriaxghu",
          "vcUuid": "254173de-ef64-4eb9-8660-3a2b19893770",
          "cid": "bafybeihiwu5rwm4oh55jqqzhbotzbfzbvtn26dxadyrgsa23tbyfcgqdli",
          "fileName": "2022-09-15T00:00:00.000Z_did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54_gc.json",
          "pvSystemDID": "did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54",
          "certificateStatus": "Active"
        }
      ]
    },
    "2022-09-18T00:00:00.000Z": {
      "entries": [
        {
          "rawInverterCID": "bafybeigvqoyoa2s5awxqre7dalgtsio3bnkgt6yqkkki6djvno5tf3n6iu",
          "vcUuid": "35da9c48-726f-4280-9218-9f54147bdb05",
          "cid": "bafybeiaonhcieqk2lqqrkt6r47eaucff7brexosuygw7b2xqgty3hdplya",
          "fileName": "2022-09-18T00:00:00.000Z_did:ethr:volta:0x1863B5eABe907FA826C16589887440539E2F44AE_gc.json",
          "pvSystemDID": "did:ethr:volta:0x1863B5eABe907FA826C16589887440539E2F44AE",
          "certificateStatus": "Active"
        },
        {
          "rawInverterCID": "bafybeigvqoyoa2s5awxqre7dalgtsio3bnkgt6yqkkki6djvno5tf3n6iu",
          "vcUuid": "b593e2a8-b13d-464c-902d-e0b02a53199c",
          "cid": "bafybeiaonhcieqk2lqqrkt6r47eaucff7brexosuygw7b2xqgty3hdplya",
          "fileName": "2022-09-18T00:00:00.000Z_did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54_gc.json",
          "pvSystemDID": "did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54",
          "certificateStatus": "Active"
        }
      ]
    }
  },
  "monthly": {},
  "pvSystems": {
    "did:ethr:volta:0x1863B5eABe907FA826C16589887440539E2F44AE": [
      "2022-09-15T00:00:00.000Z",
      "2022-09-18T00:00:00.000Z"
    ],
    "did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54": [
      "2022-09-15T00:00:00.000Z",
      "2022-09-18T00:00:00.000Z"
    ]
  }
}

=== Web3Renewables/SolarPV-Sourcing-PoC/server/examples/test_revoking_index_fixed.json
{
  "metadata": {
    "title": "Web3 Renewables Granular Certificate Index",
    "description": "Index describing the location of all GCs reporting into the Web3 Renewables Index",
    "document_type": "Development",
    "web3_renewables_did": "did:ethr:volta:0x224CbA4ae8D27Ba69793CFeFe042682B81eA77c5",
    "version": 1
  },
  "pvSystems": {
    "did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54": {
      "reporting_dates": [
        "2022-08-01T00:00:00.000Z",
        "2022-08-02T00:00:00.000Z"
      ],
      "status": "Revoked"
    }
  },
  "daily": {
    "2022-08-01T00:00:00.000Z": {
      "entries": [
        {
          "rawInverterCID": "bafybeifmwxojwausy43ajkls44y54eqan6vmz6dxhrd6pwaomhunrz7e4y",
          "vcUuid": "none",
          "cid": "bafybeicpikgrwzpieeofti6qwyx2udemzilpbply2yfkvahcnbmoaxo75m",
          "fileName": "2022-08-01T00:00:00.000Z_did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54_gc.json",
          "pvSystemDID": "did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54"
        }
      ]
    },
    "2022-08-02T00:00:00.000Z": {
      "entries": [
        {
          "rawInverterCID": "bafybeifmwxojwausy43ajkls44y54eqan6vmz6dxhrd6pwaomhunrz7e4y",
          "vcUuid": "none",
          "cid": "bafybeicpikgrwzpieeofti6qwyx2udemzilpbply2yfkvahcnbmoaxo75m",
          "fileName": "2022-08-02T00:00:00.000Z_did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54_gc.json",
          "pvSystemDID": "did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54"
        }
      ]
    }
  },
  "monthly": {
    "2022": {
      "8": {
        "entries": [
          {
            "vcUuid": "53834e7f-5efb-433a-9556-30c710cd126e",
            "cid": "bafybeidsp4psp5lkfguv3vk6vvxekckslyevc67vv3gxnx5krpcclmqqrq",
            "fileName": "2022-8-1_did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54_gc.json",
            "pvSystemDID": "did:ethr:volta:0xDE859DE701CF59Ca8Fe0a3381B946820f85E0C54"
          }
        ]
      }
    }
  }
}
